name = "this-red-rock"
main = "dist/_worker.js"
compatibility_date = "2025-07-25"
account_id = "d565ae8f6517aced5bbbb3a075fdea8f"

[assets]
directory = "./dist"
binding = "ASSETS"

[build]
command = "npm run build"

# Optional: Custom domain configuration
# route = "this-red-rock.com/*"
